// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250505100326_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Unitx", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ocupancy")
                        .HasColumnType("int");

                    b.Property<string>("Rate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "too many",
                            Area = 200,
                            CreatedAt = new DateTime(2025, 5, 5, 13, 3, 26, 254, DateTimeKind.Local).AddTicks(9559),
                            Details = "toomuch",
                            ImageUrl = "1.jpg",
                            Name = "Ziad",
                            Ocupancy = 9,
                            Rate = "5 stars",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "too many",
                            Area = 200,
                            CreatedAt = new DateTime(2025, 5, 5, 13, 3, 26, 254, DateTimeKind.Local).AddTicks(9604),
                            Details = "toomuch",
                            ImageUrl = "2.jpg",
                            Name = "Nadine",
                            Ocupancy = 9,
                            Rate = "5 stars",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "too many",
                            Area = 200,
                            CreatedAt = new DateTime(2025, 5, 5, 13, 3, 26, 254, DateTimeKind.Local).AddTicks(9607),
                            Details = "toomuch",
                            ImageUrl = "3.jpg",
                            Name = "Nour",
                            Ocupancy = 9,
                            Rate = "5 stars",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "too many",
                            Area = 200,
                            CreatedAt = new DateTime(2025, 5, 5, 13, 3, 26, 254, DateTimeKind.Local).AddTicks(9609),
                            Details = "toomuch",
                            ImageUrl = "4.jpg",
                            Name = "Amr",
                            Ocupancy = 9,
                            Rate = "5 stars",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "too many",
                            Area = 200,
                            CreatedAt = new DateTime(2025, 5, 5, 13, 3, 26, 254, DateTimeKind.Local).AddTicks(9611),
                            Details = "toomuch",
                            ImageUrl = "5.jpg",
                            Name = "Darine",
                            Ocupancy = 9,
                            Rate = "5 stars",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
